import type { CabinetItem } from '../services/cabinet';
import type { SupplementAdherence } from '../services/insights';

export interface ReportData {
  userName: string;
  exportDate: string;
  supplements: CabinetItem[];
  adherence: SupplementAdherence[];
  interactions: { supplementA: string; supplementB: string; description: string }[];
  aiInsight: string | null;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('default', { year: 'numeric', month: 'long', day: 'numeric' });
}

function adherenceRow(sup: CabinetItem, adherenceMap: Map<string, number>): string {
  const pct = adherenceMap.get(sup.name.toLowerCase());
  const pctStr = pct !== undefined ? `${pct}%` : '—';
  const timing = sup.timing ?? '—';
  const dosage = sup.dosage ?? '—';
  const frequency = sup.frequency ?? '—';
  return `
    <tr>
      <td>${escapeHtml(sup.name)}</td>
      <td>${escapeHtml(dosage)}</td>
      <td>${escapeHtml(frequency)}</td>
      <td>${escapeHtml(timing)}</td>
      <td style="text-align:center;font-weight:600;color:${pct !== undefined ? (pct >= 80 ? '#2d9d5a' : pct >= 50 ? '#d97706' : '#ef4444') : '#888'}">${pctStr}</td>
    </tr>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function buildReportHtml(data: ReportData): string {
  const adherenceMap = new Map(data.adherence.map((a) => [a.name.toLowerCase(), a.pct]));
  const activeSups = data.supplements.filter((s) => s.active);

  const rows = activeSups.map((s) => adherenceRow(s, adherenceMap)).join('');

  const interactionSection = data.interactions.length > 0
    ? `<div class="section">
        <h2>⚠ Interaction Notes</h2>
        <ul>
          ${data.interactions.map((ix) => `<li><strong>${escapeHtml(ix.supplementA)} + ${escapeHtml(ix.supplementB)}:</strong> ${escapeHtml(ix.description)}</li>`).join('')}
        </ul>
      </div>`
    : '';

  const insightSection = data.aiInsight
    ? `<div class="section insight">
        <h2>AI Insight</h2>
        <p>${escapeHtml(data.aiInsight)}</p>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font-family: -apple-system, Helvetica, sans-serif; color: #1a1a1a; margin: 0; padding: 24px; font-size: 14px; }
  h1 { font-size: 22px; font-weight: 800; margin-bottom: 4px; }
  h2 { font-size: 15px; font-weight: 700; margin-bottom: 10px; color: #333; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
  .meta { color: #6b7280; font-size: 12px; margin-bottom: 24px; }
  .section { margin-bottom: 28px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #f3f4f6; padding: 8px 10px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb; }
  td { padding: 8px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .insight { background: #f0fdf4; border-radius: 8px; padding: 14px 16px; border: 1px solid #bbf7d0; }
  .insight h2 { border-bottom-color: #bbf7d0; }
  .footer { font-size: 10px; color: #9ca3af; margin-top: 32px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
  ul { margin: 0; padding-left: 20px; }
  li { margin-bottom: 6px; line-height: 1.5; }
</style>
</head>
<body>
  <h1>Supplement Report</h1>
  <p class="meta">For: ${escapeHtml(data.userName)} &nbsp;|&nbsp; Exported: ${formatDate(data.exportDate)}</p>

  <div class="section">
    <h2>Active Supplements (${activeSups.length})</h2>
    ${activeSups.length > 0 ? `
    <table>
      <thead>
        <tr>
          <th>Supplement</th>
          <th>Dose</th>
          <th>Frequency</th>
          <th>Timing</th>
          <th style="text-align:center">30-Day Adherence</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>` : '<p style="color:#6b7280">No active supplements.</p>'}
  </div>

  ${interactionSection}
  ${insightSection}

  <div class="footer">
    Generated by Recallth. This report is for informational purposes only and does not constitute medical advice. Always consult your healthcare provider before making changes to your supplement or medication regimen.
  </div>
</body>
</html>`;
}
